# Generated by Django 6.0.4 on 2026-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Company'), ('interviewing', 'Interviewing'), ('accepted', 'Accepted'), ('completed', 'Internship Completed'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
