# Generated by Django 6.0.3 on 2026-04-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('course', models.CharField(blank=True, choices=[('BSCE', 'BS Civil Engineering'), ('BSCPE', 'BS Computer Engineering'), ('BSEE', 'BS Electrical Engineering'), ('BSIE', 'BS Industrial Engineering'), ('BSME', 'BS Mechanical Engineering'), ('BSRE', 'BS Railway Engineering')], max_length=20, null=True)),
                ('year_level', models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
