# Generated by Django 6.0.4 on 2026-04-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short personal bio or summary'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', help_text='Link to personal portfolio or GitHub'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated skills (e.g. Python, AutoCAD, MATLAB)'),
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_resumes/')),
                ('label', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Engineering Focus'", max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Marks the current/latest resume')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
