# Generated by Django 6.0.4 on 2026-04-14 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_alter_internshipapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending Admin Review'), ('approved', 'Approved')], default='pending_review', max_length=20)),
                ('technical_skills', models.IntegerField(help_text="Rate the student's technical competence (1=Poor, 5=Excellent)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(help_text="Rate the student's communication skills (1=Poor, 5=Excellent)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.IntegerField(help_text="Rate the student's professionalism (1=Poor, 5=Excellent)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('teamwork', models.IntegerField(help_text="Rate the student's teamwork ability (1=Poor, 5=Excellent)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('initiative', models.IntegerField(help_text="Rate the student's initiative and self-motivation (1=Poor, 5=Excellent)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_comments', models.TextField(help_text="Provide overall feedback on the student's performance.")),
                ('recommendation', models.CharField(choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('neutral', 'Neutral'), ('not_recommended', 'Not Recommended')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='applications.internshipapplication')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
