# Generated by Django 6.0.4 on 2026-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_export_data', 'Can export CSV data'), ('can_generate_endorsement', 'Can generate endorsement letters'), ('can_manage_roles', 'Can manage user roles/groups')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
