# Generated by Django 6.0.3 on 2026-03-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='moa_documents/')),
                ('date_signed', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moa', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='MOARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_company_name', models.CharField(max_length=255)),
                ('company_contact_person', models.CharField(max_length=255)),
                ('company_contact_email', models.EmailField(max_length=254)),
                ('justification', models.TextField(help_text='Why do you want to intern here?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing with Legal/Admin'), ('approved', 'Approved & Signed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moa_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
