# Generated by Django 6.0.4 on 2026-04-15 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_alter_internshipapplication_status'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(help_text='Overall experience (1=Poor, 5=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentorship_rating', models.IntegerField(help_text='Quality of mentorship (1=Poor, 5=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_culture_rating', models.IntegerField(help_text='Work environment and culture (1=Poor, 5=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning_rating', models.IntegerField(help_text='Learning opportunities (1=Poor, 5=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pros', models.TextField(help_text='What did you enjoy about the internship?')),
                ('cons', models.TextField(help_text='What could be improved?')),
                ('advice', models.TextField(blank=True, default='', help_text='Any advice for future interns?')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide your name on the public review')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending_review', 'Pending Admin Review')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(help_text='Ensures one review per completed internship', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='applications.internshipapplication')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'application')},
            },
        ),
    ]
