# Generated by Django 6.0.3 on 2026-03-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('course_tag', models.CharField(choices=[('BSCpE', 'BS Computer Engineering'), ('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science'), ('BSEE', 'BS Electrical Engineering'), ('BSME', 'BS Mechanical Engineering')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active MOA'), ('EXPIRED', 'Expired'), ('PENDING', 'Under Review'), ('NONE', 'No MOA')], default='NONE', max_length=10)),
                ('moa_file', models.FileField(blank=True, null=True, upload_to='moas/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MOARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
